### ISSUE TITLE
Have you considered to use brew bundle

### ISSUE THREAD

**Issue by javian** [rootbeersoup/dotfiles#1]
Have you looked into using https://github.com/Homebrew/homebrew-bundle for managing the brew dependencies instead of using the manual way you do it now ?

**Comment by darrylabbate** [comment]
So a Brewfile is definitely a simpler solution which wouldn't require any scripting on my part. The Homebrew configuration currently only exists for installing packages on a (future) fresh machine. Part of that is installing software which I don't have currently installed through Homebrew.

e.g. I'll want to install Adobe Creative Cloud via `brew cask install`. However, Adobe CC wasn't initially installed through Homebrew on my current machines. So if I were using a Brewfile, `brew bundle dump --force` would remove `adobe-creative-cloud` every time. Currently all I have to do is `echo "<package>" >> packages.txt` when I want to add a new package; I don't need to worry about accidentally removing a package. 

I'll admit I wasn't well-versed on Homebrew's bundle feature before since I wasn't aware of all the arguments you could apply in a Brewfile. I'll definitely reconsider my approach in the future if maintenance becomes too cumbersome.
